# Generated by Django 2.1.2 on 2018-12-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('credit', models.IntegerField(default=0)),
                ('teacher', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('student', models.ManyToManyField(to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', '星期一'), ('Tue', '星期二'), ('Wed', '星期三'), ('Thu', '星期四'), ('Fri', '星期五'), ('Sat', '星期六'), ('Sun', '星期天')], default='Mon', max_length=100)),
                ('number_choice', models.CharField(choices=[('1', '第一大节'), ('2', '第二大节'), ('3', '第三大节'), ('4', '第四大节'), ('5', '第五大节')], default='1', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='lession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Class'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.ManyToManyField(to='login.Time'),
        ),
    ]
