# Generated by Django 2.1.2 on 2018-12-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181206_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='login.Class')),
                ('requisiteClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='login.Class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='prerequest',
            field=models.ManyToManyField(through='login.Prerequisite', to='login.Class'),
        ),
    ]
