# Generated by Django 2.1.2 on 2018-12-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181214_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('GeneralCompulsory', '通识必修'), ('Art', '通识选修艺术类'), ('Society', '通识选修社科类'), ('Literature', '通识选修人文类'), ('Philosophy', '通识选修哲学类'), ('Others', '非通识类')], default='非通识类', max_length=1000),
        ),
    ]
