# Generated by Django 2.1.4 on 2018-12-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20181215_1426'),
    ]

    operations = [
    ]
