# Generated by Django 2.1.4 on 2018-12-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20181216_1619'),
        ('login', '0011_auto_20181223_1801'),
    ]

    operations = [
    ]
