# Generated by Django 2.1.4 on 2018-12-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20181226_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
