# Generated by Django 2.1.4 on 2018-12-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20181226_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursename',
        ),
    ]
