# Generated by Django 2.1.4 on 2018-12-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20181226_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
