# Generated by Django 2.1.4 on 2018-12-27 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_course_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course_room_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teachers',
            name='course',
            field=models.ManyToManyField(blank=True, to='login.Course'),
        ),
        migrations.AddField(
            model_name='course_room_time',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course'),
        ),
        migrations.AddField(
            model_name='course_room_time',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Classroom'),
        ),
        migrations.AddField(
            model_name='course_room_time',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Time'),
        ),
    ]
